---
- name: dotnet
  hosts: all

  vars_files:
    - vars/main.yml
    
  pre_tasks:
    - debug:
        msg: Dotnet will be installed on {{ansible_distribution}} }
    

  roles:
    - { role: role_common, tags: "role_common" }
    - { role: role_cloud, tags: "role_cloud" }
    - { role: role_tools, tags: "role_tools", vars: {tools_dbforge_install: True} }
    - { role: role_iis, tags: "role_iis" }
    - { role: role_mysql, tags: "role_mysql" }
    - { role: dotnet, tags: "dotnet" }
    # - { role: role_preend, tags: "role_preend" }
    # - { role: role_end, tags: "role_end" }