---
- name: wampserver
  hosts: all
  become: yes
  become_user: administrator
  become_method: runas

  vars:
    ansible_become_password: vc~?HBEA7t8`5q

  roles:
    - { role: common, tags: "common" }
    - { role: wampserver, tags: "wampserver" }
    - { role: 9panel, tags: "9panel" }
    - { role: sysprep, tags: "sysprep"}
