# - src: http://github.com/websoft9win/role_common
#   version: master

# - src: http://github.com/websoft9win/role_tools
#   version: master

# - src: http://github.com/websoft9win/role_cloud
#   version: master

- src: http://github.com/websoft9win/role_sqlserver
  version: master

# - src: http://github.com/websoft9win/role_iis
#   version: master

# - src: http://github.com/websoft9win/role_9panel
#   version: master

# - src: http://github.com/websoft9win/role_preend
#   version: master

# - src: http://github.com/websoft9win/role_end
#   version: master
