---
- name: phpstudy
  hosts: all

  vars_files:
    - vars/main.yml
    
  pre_tasks:
    - debug:
        msg: phpstudy will be installed on {{ansible_distribution}} }
    

  roles:
    - { role: role_common, tags: "role_common" }
    - { role: role_tools, tags: "role_tools" }
    - { role: role_cloud, tags: "role_cloud" }
    - { role: phpstudy, tags: "phpstudy" }
    # - { role: role_preend, tags: "role_preend" }
    # - { role: role_end, tags: "role_end" }